### ISSUE TITLE
response template & endpoint methods missing from the documentation

### ISSUE THREAD

**Issue by AlyShmahell** [Spianopolese/webpyux#5]
After going over `login.py` and `app.py`, I guessed that both **Login** and **Auth** should have both 'GET' and 'POST' methods at the endpoint, but I'm not sure.
Some endpoints are not specified at all in the doc, i.e.: 
```yaml
[RESTUrl]
#Ex: http://localhost/rest/page/1/menu
url: /rest/page/1/menu
```
Finally, the response template of said methods is not specified, therefore I opted to use the following:

```py
{
        "status": 200, 
        "user_data": {
            "first_name": "a",
            "last_name": "b",
            "picture": "",
            "access_token": "secret",
            "email": "a@b.com",
            "password": "hashed"
        }
    }
```
_Note: I added the password keyword because I'm not sure._  

However, the starter example still throws the following error:

```bash
PythonError: Traceback (most recent call last): File "/lib/python3.10/asyncio/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 232, in __step result = coro.send(None) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async await CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 359, in run_async await coroutine File "", line 30, in KeyError: 'first_name'
```

Please refer to the **Closed Beta Test** repository I created to demonstrate:
[https://github.com/AlyShmahell/webpyux-cbt](https://github.com/AlyShmahell/webpyux-cbt)
**Invitations have been sent.**

**Comment by Spianopolese** [comment]
There is an error in the documentation. Thanks for reporting. By tomorrow morning I update the documentation and try to understand the error that comes back to you. This type of error returns if json is not formatted as the framework expects. Phase two of the project involves the implementation of error handling.
By tomorrow morning I'll try to figure out where the mistake is and I'll let you know.

**Comment by Spianopolese** [comment]
I updated the documentation by adding the missing parts.
I downloaded your project and I followed README .
Once the server has started, the framework has successfully generated the page structure.
I edited the server.py file and added some example REST:

- the REST with the example menu
- three REST that generate three simple example widgets


I created a new branch (develop) on your project . If you want you can delete it.
Inside the app folder I added the two example widgets test.py and simple_test.py
which generate the widgets and i modified server.py to add the missing REST.

The problem you are having could be a cache problem. Once logged, the system saves user data in the browser storage. The storage is persistent unless you delete it by hand or via the logout button.
Also if it gives you other problems you can try to clear the browser cache [https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop.](https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop)

This is happening because  if there an error in a file even if you remove the error and refresh the page , the browser continues to serve the file with the error until you cancel the cache.

I hope everything is clear. I leave you some sample screens.

If there are any other hitches do not hesitate to contact me.


For me it is the first time that I have created something completely new so I apologize for the problems you are finding.

In the next few days I will try to be more present (I have been very busy at work).

[Screenshots](https://postimg.cc/gallery/056XjT7)

**Comment by AlyShmahell** [comment]
thank you, it's perfect, everything is working for this stage (login and main screen).
